config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'login', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  
  resources :users
  mount ActionCable.server, at:'/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user, foreign_key: "user_id"
    validates :body, presence: true
    scope :custom_display, -> { order(:created_at).last(5) }
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, length: { minimum: 3, maximum: 5 }, uniqueness: { case_sensitive: false }
    has_many :messages
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
def logged_in?
    !!current_user
end

def require_user
    if !logged_in?
        redirect_to login_path
    end
end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    before_action :require_user

    def index
        @messages = Message.custom_display
        @message = Message.new
    end


    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user
    def create
        message = current_user.messages.build(messages_params)
        if message.save
            ActionCable.server.broadcast "chatroom_channel", mod_message: message_render(message)
        end
    end



    private

    def messages_params
        params.require(:message).permit(:body)
    end

    def message_render(message)
        render(partial: 'message', locals: {message: message})
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    before_action :logged_in_redirect, except: [:destroy]

    def new
        
    end
    def create
        user = User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            redirect_to root_path
        else
            render "new" 
        end
   
    
    end
    def destroy
        session[:user_id] = nil
        redirect_to login_path
    end

    private

    def logged_in_redirect
        if logged_in?
            redirect_to root_path
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @user = User.all
    end
    
    def def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Welcome to the chatroom #{@user.username}"
            redirect_to root_path
        else
            render 'new'
        end
    end
    

    private
    def user_params
        params.require(:users).permit(:username, :password)
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
    <i class="circular blue users icon"></i>
    Say Something
</h4>

<div class="ui two column grid">
    <div class="twelve wide column">
        <div class="ui fluid card chatbox">
            <div class="content" id="messages">
                <div class="ui small feed" id="message-container">
                    <%= render @messages %>
                </div>
            </div>
            <div class="extra content">

                <%= form_for(@message, html: {class:"ui reply", role: "form"}, url: message_path, remote: true) do |f|%>
                <div class="field">
                    <div class="ui fluid icon input">
                        <%= f.text_field :body%>

                        <i class="borderd blue edit icon"></i>
                    </div>
                </div>

                <% end %>

            </div>
        </div>
    </div>

    <div class="four wide column">
        <div class="ui fluid card chatbox">
            <div class="content">
                <div class="ui secondary vertical pointing menu">
                    <a class="item active">
                        Home
                    </a>
                    <a class="item">
                        Messages
                    </a>
                    <a class="item">
                        Friends
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_navigation.html.erb
  <div class="ui small menu">
      <div class="ui container">

          <%= link_to 'Chatroom', root_path, class:'item'%>

          <a class="item ">
              Messages
          </a>
          <div class="right menu" id='navbar'>
              <div class="ui dropdown item ">
                  Account <i class="dropdown icon"></i>
                  <div class="menu">
                      <%= link_to 'Log in', login_path, class:'item'%>

                      <% if logged_in? %>
                      <%= link_to 'Log out', login_path, method: :delete, class:'item'%>

                      <% end %>

                      <%= link_to 'Sign Up', root_path, class:'item'%>
                  </div>
              </div>
              <div class="item">

                  <% if logged_in? %>
                  <%= link_to 'Log out', login_path,method: :delete, class:'ui red button'%>
                  <% else %>
                  <%= link_to 'Log in', login_path, class:'ui primary button'%>
                  <% end %>

              </div>
          </div>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>MessageMe</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>

<body>
  <%= render 'layouts/navigation'%>
  <div class="ui container">
    <%= yield %>
  </div>
</body>

</html>

app/views/messages/_message.html.erb
 <div class="event">
     <div class="content">
         <div class="summary">
             <em><%= message.user.username %></em>: <%= message.body %>
         </div>
     </div>
 </div>